version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      DB_HOST: mysql
      DB_DATABASE: school_manager
      DB_USERNAME: user
      DB_PASSWORD: password
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
